### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by diversys** [aleixq/images_breeze_svg_hidpi#2]
LO Version: 6.0.0.3 (x64)

![image](https://user-images.githubusercontent.com/1316513/36300142-0b33b080-1311-11e8-8f87-a3a9c3c8e6fe.png)

**Comment by ghost** [comment]
It works fine for me.
Did you set _Icon Style_ to Breeze_svg_hidpi?

**Comment by aleixq** [comment]
I have it working in ubuntu with gtk3 theme, crashes with kde4 theme... Anyway, maybe you need to post your issue (with extra information)in libreoffice bugtracker.
